### ISSUE TITLE
What's the name of the identifier specified after the 'behavior' keyword?

### ISSUE THREAD

**Issue by echebbi** [gemoc/ale-lang#142]
## Motivation

Each source file starts with the `behavior` keyword:

```
behavior some.qualified.name;
```
This keyword provides a way to define what I called a "semantics namespace" [in the docs](https://github.com/echebbi/ale-lang-docs/blob/77c76e3/content/reference/syntax.md). We need to reference this "semantics namespace" both in docs and source code but AFAIK we have no clear name to identify it. We should define one to prevent ambiguities. 

## Reminder of this keyword's purposes

 - dynamic classes are put in an EPackage named after the "semantics namespace"

I'm not aware of any other purpose.

## Propositions

 - semantics namespace
 - behavior namespace
 - behavior module
 - behavior identifier

"behavior" is already used across the codebase so I would favor it over "semantics". @pjeanjean @dvojtise @fcoulon any suggestion/feedback?

**Comment by dvojtise** [comment]
Actually, it is still unclear for me about the exact expected semantic of different combination:
given an ecore (using oclinecore syntax)

```
package helloworld : helloworld = 'http://www.example.org/helloworld'
{
	class HelloWorld
	{
		operation greeting() : String[?];
	}
}
```

we can define in ale (from base example):
```
behavior helloworld;
open class HelloWorld {
	String msg := 'Hello world!';
	override EString greeting() {
		result := self.msg;
	}
	@main
	def void entryPoint() {
		self.greeting().log();
	}
}
```

but what about this scenario (coming from Kermeta):
```
behavior myTransformation;
open class helloworld.HelloWorld {
	@main
	def void generate() {
		// do some transformation
	}
}
```

which is supposed to be reopening the same class but adding another operation
(and possibly attributes)
Operations coming from different "semantic namespaces" could be combined to produce a larger tool 

However, I'm not 100% sure that we need to clearly identify those semantic namespaces, since this is the assembly (done in the .dsl file) that actually combines everything, and we never use that name explicitely.

for me this keyword is mainly a shorthand to not type the full qualified name in the `open class`

**Comment by echebbi** [comment]
> for me this `behavior` keyword is mainly a shorthand to not type the full qualified name in the `open class`

Actually you can write:

```kotlin
behavior myTransformation;

open class HelloWorld {
	@main
	def void generate() {
		// do some transformation
	}
}
```

The only reason to type the fully qualified name in the `open class` is when you have namesakes (i.e. two EClass with the same name, likely coming from two different metamodels). 

AFAIK the "semantic namespace" is currently used only when creating EClass from dynamic classes. For instance, interpreting the following code:

```kotlin
behavior myTransformation;

class MyDynamicClass {

}
```

will create a new EClass called `MyDynamicClass` in an EPackage called `myTransformation`.

> However, I'm not 100% sure that we need to clearly identify those semantic namespaces, since the assembly is done in the .dsl file by combines everything, and we never use that name explicitly.

We would with namesakes:

*a.ale*
```kotlin
behavior a;

class Hello {}
```
*b.ale*
```kotlin
behavior b;

class Hello {}
```
*c.ale*
```kotlin
behavior c;

open class Main {
    
    @main
    def void main() {
        a::Hello a := a::Hello.create();
        b::Hello b := b::Hello.create();
    }

}
```

**Comment by dvojtise** [comment]
From what you're saying, this keyword is actually useless if the ale file doesn't define any dynamic class (ie. not an open class but class only)
In case the ale file define a dynamic class, this keywork is mandatory and equivalent to the `package`  keyword.

In any case,
I don't like having a single  declaration for the package, this sound inspired from java, but in java you cannot define several classes in a single file.

I would prefer a clearer syntax such as the one of oclinecore:
open class would be defined at the root of the ale file and new dynamic classes would be defined in a well define block (with bracket for example)

something like:
```kotlin
package a {
   class Hello {}
}
package b {
   class Hello {}
  open class Main2 {} // error/warning open class doesn't need package declaration
}
// this resolve to any class named "Main" in the resolution scope (defined by the considered .dsl file)
// if ambiguous in the resolution scope, the editor must report an error
open class Main {
    @main
    def void main() {
        a::Hello a := a::Hello.create();
        b::Hello b := b::Hello.create();
    }
}
class Foo {}  // error not defined in a package
```

**Comment by dvojtise** [comment]
in Kermeta 1&2, there was also a single package declaration at the top of the file, but this was also used for Name resolution of the aspectized class (which isn't the case in ALE). It also defined a shorthand syntax for simplifying access to other packages from the given file.

cf. http://www.kermeta.org/docs/kermeta2/html/Kermeta-Manual.docb/Kermeta-Manual.docb.single.html#section_first_program.link and http://www.kermeta.org/docs/kermeta2/html/Kermeta-Manual.docb/Kermeta-Manual.docb.single.html#section_weaving.link


So either we stick to a single `package` keyword and use it for resolution everywhere, 
or we use package blocks.

**Comment by echebbi** [comment]
> From what you're saying, this keyword is actually useless if the ale file doesn't define any dynamic class (ie. not an open class but class only)
> In case the ale file define a dynamic class, this keywork is mandatory and equivalent to the package keyword.

To the best of my knowledge, yes.

> I would prefer a clearer syntax such as the one of oclinecore. [...] So either we stick to a single `package` keyword and use it for resolution everywhere or we use package blocks

IMO we should get rid of the `behavior` declaration on the top of the file if possible because it is really disturbing. We may consider re-introducing one later if we have the need. There is however a third option: do not provide any `package` keyword at all and create all dynamic classes in a "default" package (e.g. `http://gemoc.org/ale-lang/dynamic_classes`). Questions would then be:

 - are namesakes likely to happen (only considering dynamic classes)?
 - do we want to handle namesakes or merely forbid them?

IMO it hugely depends on the scope of ALE. Small to medium DSLs can be easily handled with a few files and without even worrying about namesakes, but if in the future we plan to target bigger DSLs as well (e.g. a complex workflow engine with scripting, remote computing, etc.) we may want to provide a package-like hierarchical layout featuring visibility modifiers.

By the way, if we opt for package blocks I would however allow `open class` when `package` matches ecore's EPackage:

```kotlin
package helloworld {
     class Greet {} // creates a new EClass in the EPackage "helloworld"
     open class HelloWorld {} // adds attributes/methods to the existing EClass called "HelloWorld"
     open class FSM {} // no FSM EClass in the helloworld metamodel -> error
}
```

**Comment by dvojtise** [comment]
We should not restrict to small to medium DSLs, 

I'm not a fan of a default package (what is its name ? can it conflict in some situation ? there is higher risk of conflict when combining DSLs / DSL parts)

I think that if we have the possibility to create dynamic classes in ALE, then we need to keep the possibility to organize the classes in package as the dynamic part can be complex too, otherwise we are saying that the user **must** write his dynamic classes directly in ecore (and then completely remove the "new dynamic class" feature from ALE) 
Having the possibility to write the dynamic classes in ecore is important but as this is less "agile" (especially for small DSLs),  I think we need to keep both mechanism

Ok for you last point to allow open class in package, but in that case, we must forbid full qualified name
```kotlin
package helloworld {
     open class helloworld.HelloWorld {} // error, does it stand for helloworld.HelloWorld or helloworld.helloworld.HelloWorld ?
}
```

**Comment by echebbi** [comment]
Taking everything into account I would then go for a `package x.y.z;` at the top of the file. Let me explain.

First, I dislike the fact that the `package x.y.z {}` block adds another indentation level. Second, I don't think we want to encourage users to open/define several packages in a single source file: it would likely harm both the cohesion and clarity of the code.

As such, I would suggest the following approach:

```kotlin
package x.y.z; // the name of the EPackage we want to open/define

// Create a new EClass called "SomeDynamicClass " in the EPackage called "x.y.z"
// Shows an error if an "SomeDynamicClass" is already defined in a metamodel and belongs to the "x.y.z" EPackage.
class SomeDynamicClass {}

// Add attributes/methods to the EClass called "SomeStaticClass " in the EPackage called "x.y.z"
// Shows an error if "SomeStaticClass" isn't defined in any metamodel or doesn't belong to the "x.y.z" EPackage
open class SomeStaticClass {}
```

Pros:
 - more intuitive because consistent with Java (you said that you didn't like it because "this sound inspired from java, but in java you cannot define several classes in a single file" but IMHO that's clearly not an issue. As a matter of fact Xtend uses a `package` declaration and allows for several top classes in a single source file)
 - favor cohesion by preventing mixing classes belonging to different packages
 - less likely to end up with namesake issues and more likely to understand them (and how to address them)

Cons:
 - implementing the semantics of a language involving *X* metamodels requires at least *X* source files (looks more like a good constraint than like a real drawback from my point of view)

**Comment by dvojtise** [comment]
Having package on top might be a solution but in that case some user can consider that this is a global directive
About the statement "_// Shows an error if "SomeStaticClass" isn't defined in any metamodel_" do you mean that it still allow lazy matching for open class ? It may sound counterintuitive as one might expect that the SomeStaticClass is part of x.y.z.  (we currently have no way to know which class was actually opened and top directive is misleading)
If we use `package x.y.z;` at the top of the file I would propose to remove the lazy matching of open class.

However, as this lazy matching is quite nice in some situation (in order to  enable some simple  duck typing and write ALE aspects that match several metamodels)


I think the only coherent approach is:
```kotlin

package x.y.z { // the name of a EPackage we want to open/define
   // Create a new EClass called "SomeDynamicClass " in the EPackage called "x.y.z"
   // Shows an error if an "SomeDynamicClass" is already defined in a metamodel and belongs to the "x.y.z" EPackage.
   class SomeDynamicClass {}
   // Add attributes/methods to the EClass called "SomeStaticClass1 " in the EPackage called "x.y.z"
   // Shows an error if "SomeStaticClass1" isn't defined in any metamodel AND doesn't belong to the "x.y.z" EPackage
   // doesn't allow duck typing
   open class SomeStaticClass1 {}
}

// Add attributes/methods to the EClass called "SomeStaticClass2 "  from any EPackage
// Shows an error if "SomeStaticClass2" isn't defined in any metamodel OR if several classes have this name
// allow duck typing
open class SomeStaticClass2 {}
// Add attributes/methods to the EClass called "SomeStaticClass3 " in the EPackage called "x.y.z"
// Shows an error if "SomeStaticClass3" isn't defined in any metamodel AND doesn't belong to the "x.y.z" EPackage
// doesn't allow duck typing
open class x.y.z.SomeStaticClass3 {}
// class SomeDynamicClass2 {}  // error, not defined in a package
```

**Comment by echebbi** [comment]
> Having package on top might be a solution but in that case some user can consider that this is a global directive

What do you mean by "global directive"? I propose it as a way to indicate "following classes must be part of the x.y.z package, whether open or not".

> About the statement "// Shows an error if "SomeStaticClass" isn't defined in any metamodel" do you mean that it still allow lazy matching for open class ?

No, by _"Shows an error if "SomeStaticClass" isn't defined in any metamodel or doesn't belong to the "x.y.z" EPackage"_ I meant that the declaration is valid only when the open class is defined in a metamodel _and_ belongs to the x.y.z package.

I think we agree on the semantics on the `package` thing, but we disagree on whether it should be a single statement or a block.

> However, as this lazy matching is quite nice in some situation (in order to enable some simple duck typing and write ALE aspects that match several metamodels)

That's the key point. Is it actually helpful to be able to reuse the exact same aspect on several metamodels? I would rather think that the ALE aspects would need to be tailored to each metamodel anyway and that duck typing "by default" (people won't bother with a `package {}` block if the code works without one) may actually be dangerous (especially if we keep the practice to open/define several classes in a single source file).

Opportunistic reuse of aspects looks unlikely to me (please contradict me if your experience tells the opposite), so if it has to be foreseen I'd prefer to make it explicit, e.g.:

```kotlin
// one of the following statements indicate that below aspects will match classes from ANY package
// another approach would be to remove the package statement when we want duck typing 
// but that would be the same as duck typing "by default"
package **;
any package;

// Forbidden here
class SomeDynamicClass {}

// Will match any EClass named "SomeStaticClass"
// Since it's in a "package **;" developers are aware of the fact that this aspect
// is kind of "public" and that it should be modified with care not to break client code
open class SomeStaticClass {}
```

**Comment by dvojtise** [comment]
Using a single statement on top of the file (instead of block) may work with the following addition to your rules:

1>
> // or match a selected set of packages:
> package x.y.z;
> package a.b.c;

do you mean that you can repeat the package key ?
I would prefer a regular expression on a single statement.

2>
// Forbidden with "match any package statement"
// AND forbidden if using a "match of selected set of package"
class SomeDynamicClass {}

3>
optional: if forbidden as above allow:
```kotlin
class x.y.z.SomeDynamicClass3 {}
```

**Comment by echebbi** [comment]
I'm OK with those but that's under the strong assumption that aspect reuse is never opportunistic (even though we can introduce workarounds laters); does it look reasonable for you as well?

**Comment by combemale** [comment]
What about having a discussion about this next time during the SLE dev meeting? 
I will be there next Tuesday. 

Cheers, 
benoit

**Comment by dvojtise** [comment]
Aspect can be designed to be opportunistic, if you use your regular expression 
```kotlin
package **;
```

This solution looks good to me too.

**Comment by echebbi** [comment]
Great! 

@combemale Didier will be on holiday next week but I'll prepare a slide to propose the solution to the rest of the team.

**Comment by echebbi** [comment]
After discussing with the other members of the team the approved solution was to keep the current semantics of the `behavior` keyword (but consider renaming it, e.g. as `extension`).

The rational is that fixing #151 should mitigate the namesake issue and that opening a class which has namesakes coming from available Ecore models (the ones specified in the .dsl) requires an fully qualified name anyway.

We'll reopen later if some issues are uncovered later on; for now it spares us some work.
