### ISSUE TITLE
Ale dark theme not deployed ?

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#145]
There's a dark theme for ale editor since https://github.com/gemoc/ale-lang/issues/94

However, I'm not sure it is correctly deployed

the name in the manifest https://github.com/gemoc/ale-lang/blob/6558e9a4c9336496e0cbec2635d566cc9207e86a/plugins/org.eclipse.emf.ecoretools.ale.xtext.ide.theme/META-INF/MANIFEST.MF#L4 looks wrong and the plugin is thus not included in the feature.xml

**Comment by echebbi** [comment]
The name is "correct" (at least set on purpose, see https://github.com/gemoc/ale-lang/pull/103). But I indeed forgot to include the plug-in in the feature.
