### ISSUE TITLE
Variable type checking not enforced

### ISSUE THREAD

**Issue by pjeanjean** [gemoc/ale-lang#17]
The following code does not generate any error:
```
behavior testale_behavior;

open class ClassA {
	@main
	def void run() {
		int i := false;
		i.log();
	}
}
```

An error should be displayed, at least in the editor.

**Comment by fcoulon** [comment]
It reports an error with the last build
Can you retry with the last snapshot of ALE to confirm it s fixed ?

**Comment by pjeanjean** [comment]
Looks good, thanks.
