### ISSUE TITLE
Resolution of methods with list parameters not working

### ISSUE THREAD

**Issue by pjeanjean** [gemoc/ale-lang#20]
When using lists (or sequences in ALE) as parameters for a method, the engine is unable to resolve the right method to use.

For example, the following minimal behavior file:
```
behavior testale_behavior;

open class ClassA {
	def int mysum(Sequence(Integer) list) {
		result := list->sum();
	}
	
	@main
	def void run() {
		Sequence(Integer) list := Sequence{1, 2, 3};
		self.mysum(list).log();
	}
}
```

Returns the following output:
```
Couldn't find the 'mysum(EClassifier=ClassA,java.util.ArrayList)' service
```

**Comment by dvojtise** [comment]
Not only the method cannot be called, but internally, the parameter cannot be used properly.
various error occurs 

some example:

![image](https://user-images.githubusercontent.com/661468/63003217-09b94300-be78-11e9-8205-f6abd51349ca.png)

**Comment by dvojtise** [comment]
or
![image](https://user-images.githubusercontent.com/661468/63003720-1d18de00-be79-11e9-9269-294bd86ba2c7.png)

**Comment by echebbi** [comment]
It looks like the issue only occurs when the Sequence is declared within an operation. e.g. the following code is correctly checked & interpreted:

```
behavior helloworld;

open class HelloWorld {
	
    Sequence(Integer) list;
	
    def int mysum(Sequence(Integer) list) {
        result := list->sum();
    }
	
    @main
    def void run() {
        self.list := Sequence{1, 2, 3};
        self.mysum(self.list).log();
    }
}
```

> ***Note:** The assignation `result := list->sum()` is not handled by the TypeChecker*(Expected [ecore::EInt] but was [Nothing(Sum can only be used on a collection of numbers.)), *but that seems to be another bug.*
