### ISSUE TITLE
Typechecker not called on GEMOC official example

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#26]
when installing the GEMOC ALE official example I was expecting it to be configured as a nominal configuration and to be able to raise typechecking errors

but introducing errors in the ALE code does not raise any error. (both trying to change Ecore attribute or local attribte for example)

might be related to https://github.com/gemoc/ale-lang/issues/4

note: using current ale distributed with GEMOC

**Comment by dvojtise** [comment]
Actually, what are the correct keys to be used in the dsl file ?

the ALE example uses:
- syntax=
- behavior=

and the GEMOC ALE example uses:
- ecore=
- ale=

for the same information

*syntax/behavior* allows to have some typechecking, and *ecore/ale* allows to start the GEMOC ALE engine :thinking:

**Comment by dvojtise** [comment]
Need to harmonize the keys of the dsl file: one purpose = one keyword

**Comment by dvojtise** [comment]
Decision: must change to `ecore` and `ale` keywords instead of `syntax` and `behavior`

**Comment by ebousse** [comment]
Same issue here: when using ALE in GEMOC (with TFSM official example) I have no auto-completion and it can barely detect any error.

**Comment by dvojtise** [comment]
the current workaround is to duplicate the key to use both ecore and syntax and tio use both ale and behavior  (referencing the same files)
