### ISSUE TITLE
Expected Foo but was [EClassifier=Foo] on a collection navigation at(i) or first()

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#30]
what can cause this kind of messages ?

```
fcl::Event evt0 := fcl::ExternalEvent.create();
RuntimeContext context := fclModel.runtimeContext;
fcl::Event evt1 := context.receivedEvents->at(1); 
```

the typechecker reports `Expected Event but was [EClassifier=Event]` on the line with the `->at(1)`

same error with `->first()`
note: the receivedEvent is defined as  reference in a vm.ecore file that is referenced in the dsl file.

**Comment by dvojtise** [comment]
attached some smaller projects that reproduce the issue

[ale-lang-issue-30.zip](https://github.com/gemoc/ale-lang/files/3293122/ale-lang-issue-30.zip)
apparently, the typechecker seems to have several version of the same Eclassifier and/or try to infer type from previous assignment

for example I can get this error too
`Expected [EClassifierLiteral=ExternalEvent] but was [EClassifier=Event]`
on the following lines :
```
Event evt1 := fcl::ExternalEvent.create();
evt1 := self.runtimeContext.receivedEvents->at(1);
```
despite the declared type is Event...

**Comment by fcoulon** [comment]
1f4e46e38bd706bb7861dc0d746463c4c4ae8867 should fix the error marker in:
~~~
fcl::Event evt0 := fcl::ExternalEvent.create();
~~~
and 60185467ef77c51eceb9d10dd608b0c12bb73d04 should fix the error marker in:
~~~
RuntimeContext context := fclModel.runtimeContext;
fcl::Event evt1 := context.receivedEvents->at(1); 
~~~

**Comment by fcoulon** [comment]
Can I close?
