### ISSUE TITLE
use fully qualified name when reporting type error

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#32]
related to #30 and #31 

when several Eclass exist with the same name the error message is not clear enough

In my example
![image](https://user-images.githubusercontent.com/661468/60422604-a5566300-9bec-11e9-82cb-f369ace723de.png)

the error can easily be solved using a fully qualified name on the variable, but the message does not inform about the package used by ALE in the expression.

**Comment by fcoulon** [comment]
Should be fixed by c42171148fce941dea76b3fcf5a51326dba9074b

**Comment by echebbi** [comment]
Can this issue be closed?
