### ISSUE TITLE
documentation about collection services is incomplete

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#35]
the ale documentation has a list of services on collections 
http://gemoc.org/ale-lang/reference.html#services-for-collections

this is very useful as an overview of these services :smiley:

however, it seems to be incomplete according to https://www.eclipse.org/acceleo/documentation/aql.html#SyntaxReference

for example, it does not refers to `filter` 

(other may be missing too, but I haven't checked)

**Comment by echebbi** [comment]
Closing as it is now reported in the documentation's repository: https://github.com/echebbi/ale-lang-docs/issues/6
