### ISSUE TITLE
"Double" does not seem to be accepted as parameter type

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#36]
in the following example

```
behavior bugs;

open class Foo {
	
	@main 
	def void main() {
		self.myMethod1(1.1);
		self.myMethod2(2.2);
		self.myMethod3(3.3);
	}
	
	def void myMethod1(Double d) {
		('myMethod1').log();
		self.myDouble1 := d;
	}
	def void myMethod2(Real d) {
		('myMethod2').log();
		self.myDouble2 := d;
	}
	def void myMethod3(ecore::EDouble d) {
		('myMethod3').log();
		self.myDouble3 := d;
	}
}
```

myMethod1 is never called (without error message)

![image](https://user-images.githubusercontent.com/661468/60511684-d6a95e80-9cd2-11e9-9b2b-17b2fcf0ec12.png)

strangely, the assignment `self.myDouble1 := d;` seems to typecheck correctly in the editor (ie. using `Doooble` as type, correctly reports an error) but when the model is run, the method is ignored.
[ale-lang-issue-36.zip](https://github.com/gemoc/ale-lang/files/3349924/ale-lang-issue-36.zip)

[ale-lang-issue-36-models.zip](https://github.com/gemoc/ale-lang/files/3349947/ale-lang-issue-36-models.zip)

**Comment by dvojtise** [comment]
note: the fact that the method is ignored without any warning is probably related to https://github.com/gemoc/ale-lang/issues/28 (method not being found at runtime ?)

**Comment by echebbi** [comment]
The interpreter now stops with a more "accurate" error message:

```
Couldn't find the 'myMethod1(EClassifier=HelloWorld,java.lang.Double)' service
    At helloworld/src-ale/helloworld.ale:15
```

There's indeed an issue with `Double`; `myMethod2` and `myMethod3` run without issue.
