### ISSUE TITLE
Stopping the execution on unexpected error

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#38]
Currently, the interpreter continues to execute even in case of very strange errors (such as missing method), 0 divisions, ...).
At most, it reports the error (see https://github.com/gemoc/ale-lang/issues/28)

while this can make sense for constraint checking to continue to check all constraints even if one fails, I don't think it is relevant while running a model.
I would prefer my execution to stop because in that case, I'm not confident anymore about the remaining of the execution.

If one thinks the execution should continue after such error, why not, but in that case, an option of the interpreter should enable/disable this

**Comment by dvojtise** [comment]
Please implement that

this is even more important because the engine does not even stop on a java exception.

As a tentative workaround for #37, I implemented a simple java service that raises a java exception.

This exception is completely ignored, the engine neither stop , nor print any message.

**Comment by fcoulon** [comment]
fc6fd8d386f1f44ebab18dff36da5b87fb1de962 should do the job
Can you test it  on your use cases ?

**Comment by dvojtise** [comment]
This does not seem to be enough, the evaluation seems shortened a little but when run in GEMOC, it continues to next steps

**Comment by dvojtise** [comment]
Additionally, the evaluation diagnostic is lost (not printed anymore) (even if it was on a simple message on System.out, this information is useful)

**Comment by echebbi** [comment]
Re-opening this issue because it is not fixed yet. For instance, I noticed that using a non existing feature does not produce any error at runtime, even though the type checker warns about the feature not being defined:

```ale
behavior helloworld;

open class HelloWorld {
	
    @main
    override void greeting () {
        self.a -= '';
    }
}
```
There are also several places in the code where a `// TODO` indicates that an error occured but where nothing is reported to the user, such as here:
https://github.com/gemoc/ale-lang/blob/be6e174471c0992d9f430c676a05194c1c59bf36/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/DynamicFeatureRegistry.java#L163-L181

I believe we should take a deeper look into this to make sure that unexpected situation are properly handled.

**Comment by echebbi** [comment]
Some syntax errors are not caught either.

For instance, running the following code leads to a NPE that stops the execution without any warning:
```
open class HelloWorld {
	
	String open := 'Hello world!';

	...
}
```

**Comment by echebbi** [comment]
Generally speaking, it seems that any error that does not occur during the interpretation of the AST is not reported to the user.

For instance, I had issues with my XMI file being incorrectly formatted but when running the ALE script the execution was just stopping without any error message, neither in the console nor in the _Error Log_ view.

It looks like the exception is properly caught here though:
https://github.com/gemoc/ale-lang/blob/ad1eb5b0d9978127dcbe550095d4eccb86852844/plugins/org.eclipse.emf.ecoretools.ale.ide.ui/src/org/eclipse/emf/ecoretools/ale/ide/ui/launchconfig/RunModelAction.java#L118-L121

The stacktrace is printed in a development environment but not when ALE is installed in an Eclipse instance. Didn't have the time to investigate yet.

**Comment by dvojtise** [comment]
I Reopen the issue since there are some other case where the execution isn't properly stopped:


based on a simple modification of the HelloWorld example
```
behavior helloworld;

open class HelloWorld {
	String msg := 'Hello world!';
	HelloWorld sibling;

	@main
	def void entryPoint() {
		('start').log();
		// self.sibling := helloworld::HelloWorld.create();
		self.sibling.msg := 'new message';
		('end').log();
	}
}
```


The second message (end) is never shown because of the error on the `self.sibling.msg`  (self.sibling is null)
Additionally, the error is not reported in any of the consoles ...

same issue with uninitialized variables as in the following example:
```
	@main
	def void entryPoint() {
		('start').log();
		HelloWorld aHW;
		aHW.msg := 'new message';
		('end').log();
	}
```
