### ISSUE TITLE
Typecheck error when initializing Sequence

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#42]
according to #29 initializing a sequence feature is done using the `:= Sequence{};`

however, this raises a typechecker exception in the editor.
( Expected Collection(helloworld::HelloWorld) but was [Sequence(Nothing(Empty Sequence defined in extension))]  when using a variable
or Expected [ecore::EEList] but was [Sequence(Nothing(Empty Sequence defined in extension))] when using a feature

![image](https://user-images.githubusercontent.com/661468/62129866-064e8500-b2d8-11e9-9ccb-fd7e3391da34.png)

![image](https://user-images.githubusercontent.com/661468/62129887-15353780-b2d8-11e9-8267-5aabff249dcd.png)

step to reproduce: get the ale helloworld example, add the lines as in the figures.

**Comment by dvojtise** [comment]
Similar issue when trying to assign the result of an operation that is typed using a Sequence

**Comment by echebbi** [comment]
Looks like the type checker does not raise any error anymore:

![image](https://user-images.githubusercontent.com/25926433/66494800-83f0f700-eab8-11e9-8124-72ac7fd4a850.png)

However the interpreter is triggered by the declaration of `helloworlds2` on line 11: if I don't specify an initial value the execution fails:
```
Run helloworld.dsl
------------
greeting(Object=EClassifier=HelloWorld) with arguments [org.eclipse.emf.ecore.impl.DynamicEObjectImpl@6bbc3547 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@60645c50 (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))] failed:
	null

[AQL eval fail] At line 18 in C:\Users\echebbi\runtime-EclipseApplication(1)\helloworld\model\helloworld.ale :
Diagnostic ERROR source=null code=0 null [Diagnostic ERROR source=org.eclipse.acceleo.query code=0 greeting(Object=EClassifier=HelloWorld) with arguments [org.eclipse.emf.ecore.impl.DynamicEObjectImpl@6bbc3547 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@60645c50 (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))] failed:
	null data=[org.eclipse.acceleo.query.runtime.AcceleoQueryEvaluationException: greeting(Object=EClassifier=HelloWorld) with arguments [org.eclipse.emf.ecore.impl.DynamicEObjectImpl@6bbc3547 (eClass: org.eclipse.emf.ecore.impl.EClassImpl@60645c50 (name: HelloWorld) (instanceClassName: null) (abstract: false, interface: false))] failed:
	null]]
An error occured during evaluation of a query
```
