### ISSUE TITLE
Typecheck error when using aspect on subclass

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#45]
When defining attribute aspect on a subclass

then, in several situations the typechecker fails to find the attribute and produce errors.

in this figure, B inherits from A in the ecore.

![image](https://user-images.githubusercontent.com/661468/62462241-2aeaa700-b787-11e9-8218-0faeb1998725.png)

Also note that, if there is no `open class A`  then the faulty lines correctly typechecks...
![image](https://user-images.githubusercontent.com/661468/62462335-73a26000-b787-11e9-9102-fd3125d0b4da.png)

project for reproducing this bug:
[ale-lang-issue.zip](https://github.com/gemoc/ale-lang/files/3467420/ale-lang-issue.zip)

**Comment by dvojtise** [comment]
apparently, the declaration order of the open classes in the ale file matters

in the following example, inverting the `open class ecore.EClassifier` and `open class ecore.EClass`
will have the error on one line or the other (attrOnEClass or attrOnEClassifier)
![image](https://user-images.githubusercontent.com/661468/62462863-c9c3d300-b788-11e9-964d-c953733b2551.png)

**Comment by dvojtise** [comment]
should be fixed by 
https://github.com/gemoc/ale-lang/commit/3e41bfc1c47a8da0ee14254ee9dde62a125702bb

**Comment by echebbi** [comment]
Can't reproduced on master 265f946. Assumed fixed.
