### ISSUE TITLE
Variables cannot be declared without initial value within operations

### ISSUE THREAD

**Issue by echebbi** [gemoc/ale-lang#56]
## Bug description

Declaring a variable without initializing it within an operation makes the interpreter crash at runtime without any error message. Indeed, an unexpected `NullPointerException` is thrown and never handled.

## How to reproduce

1. Create a project with the **Hello world!** example wizard
2. Replace the content of _helloworld.ale_ by the following code:
```
behavior helloworld;

open class HelloWorld {
	
	@main
	override void greeting () {
		Integer i;
	}

}
```
3. Run the interpreter

## Explanation

When a new variable is declared within an operation, the statement is evaluated by [MethodEvaluator.caseVariableDeclaration](https://github.com/gemoc/ale-lang/blob/4d429d28490b8a17a0a9c4162471f03ded1dd470/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/MethodEvaluator.java#L121). This method starts by asking AQL to evaluate the initial value of the variable:

https://github.com/gemoc/ale-lang/blob/4d429d28490b8a17a0a9c4162471f03ded1dd470/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/MethodEvaluator.java#L122

The problem is that there is no initial value, so AQL is asked to evaluate `null`, which leads the AQLEngine to return a null result and ultimately raising the `NullPointerException` within  [MethodEvaluator.aqlEval](https://github.com/gemoc/ale-lang/blob/4d429d28490b8a17a0a9c4162471f03ded1dd470/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/MethodEvaluator.java#L358):
https://github.com/gemoc/ale-lang/blob/4d429d28490b8a17a0a9c4162471f03ded1dd470/plugins/org.eclipse.emf.ecoretools.ale.core/src/org/eclipse/emf/ecoretools/ale/core/interpreter/MethodEvaluator.java#L354-L358

The exception thrown is never caught and stops the execution without warning the user.

## Solution

Two solutions can be considered:

1. Initializing the variables to a default value
2. Preventing the user from declaring unitialized variables and providing explicit error messages

**Comment by dvojtise** [comment]
got the same issue yesterday but did not take time to report it ...

**Comment by dvojtise** [comment]
note: 

if the variable is an object (and not a primitive type) one may initialize the variable to _null_ on purpose.

**Comment by echebbi** [comment]
Just did a little test to check whether attributes have a default value, and it seems that:

- **Integer** — initialized to `0`
- **String** — initialized to `null`
- **Boolean** — initialized to `false`

I believe that these are the default values used by EMF so we can keep them, however we should make sure to be consistent and to initialize variables declared within an operation to the same values.

Here is the ALE code I used:

```
behavior helloworld;

open class HelloWorld {
	
	Integer i;
	String s;
	Boolean b;
	
	@main
	override void greeting () {
		('' + self.i).log();
		self.s.log();
		('' + self.b).log();
	}

}
```
