### ISSUE TITLE
document all available services

### ISSUE THREAD

**Issue by dvojtise** [gemoc/ale-lang#61]
The documentation should be improved in order to help the user to find all available services for a given class, primitive type, collection, ...

- some services come from ALE itself
- some come from AQL (one of my input documentation is https://www.eclipse.org/acceleo/documentation/ but it isn't easy to read as it hasn't a table of content)
- some come form OCL (one of my input documentation is https://wiki.eclipse.org/Acceleo/OCL_Operations_Reference )
- and some come from unknown source. 

ex of unknown source `Integer.toDouble()` does work but I have no idea where it comes from since none of the above document lists it.

![image](https://user-images.githubusercontent.com/661468/63516123-aa4cda00-c4ec-11e9-9d1a-c612a78fc9d5.png)

**Comment by echebbi** [comment]
Just for the record: it seems that the `toDouble` service comes from AQL. Here is the commit that provided it:

- [https://git.eclipse.org/c/acceleo/org.eclipse.acceleo.git](https://git.eclipse.org/c/acceleo/org.eclipse.acceleo.git/commit/?id=5a8362c89c3b2d92ec2008fa98f19586374bff27)

**Comment by echebbi** [comment]
Related issue: [documentation about collection services is incomplete #35](https://github.com/gemoc/ale-lang/issues/35)

**Comment by echebbi** [comment]
Closing as it is now tracked in documentation's repository: https://github.com/echebbi/ale-lang-docs/issues/7
