### ISSUE TITLE
Ability to select the instance and the main method to execute when launching the interpreter

### ISSUE THREAD

**Issue by echebbi** [gemoc/ale-lang#86]
## Current Behavior

When launching an ALE script we provide two information:

 - the DSL file (_.dsl_) providing the metamodel and its semantics
 - the model file (_.xmi_) defining the model on which the semantics should be applied

Currently, ALE's launcher:

1. Parse the model
2. Find the first method annotated with `@main`
3. Call this method on the model's root element

## Issues

This behavior causes the following problems:

- if the root element is not of the type expected by the `@main` method ALE doesn't show any error, which can confuse the user
- if several `@main` methods are available ALE will arbitrarily select the first one, whereas the user may want to run another one
- it is impossible to run a `@main` method on a model element which is not at the root of the XMI file

## Expected Behavior

At runtime...

### ... when there are no ambiguity

If the semantics provides only one `@main` method and the model contains only one element that supports the semantics then this method should be run automatically on the corresponding element.

### ... where there is an ambiguity

If the semantics provides several `@main` methods or if the model contains several elements that support the semantics then the Launch Delegate should prompt a dialog to ask the user to clarify their will.

A similar behavior [is provided by the GEMOC Studio](http://gemoc.org/studio_docs/2.3.1/Guide.html#modeling-workbench-executing-model-section).

## Related Issue

#60 — Create a Run Configuration when the context-menu shortcut is used to run the interpreter

**Comment by dvojtise** [comment]
about calling the  creation of the launch conf when performing a run
the relevant code is here in GEMOC: https://github.com/eclipse/gemoc-studio-modeldebugging/blob/641a6ac6db61c0c84d98df07b19647225a9caf75/simulationmodelanimation/plugins/org.eclipse.gemoc.dsl.debug.ide.ui/src/org/eclipse/gemoc/dsl/debug/ide/ui/launch/AbstractDSLLaunchConfigurationDelegateUI.java#L196

then the creation of the appropriate launch conf with default parameters is done in the implementation sub classes https://github.com/eclipse/gemoc-studio-modeldebugging/blob/master/simulationmodelanimation/plugins/org.eclipse.gemoc.dsl.debug.ide.sirius.ui/src/org/eclipse/gemoc/dsl/debug/ide/sirius/ui/launch/AbstractDSLLaunchConfigurationDelegateSiriusUI.java or https://github.com/eclipse/gemoc-studio-modeldebugging/blob/641a6ac6db61c0c84d98df07b19647225a9caf75/framework/execution_framework/plugins/org.eclipse.gemoc.executionframework.engine.ui/src/org/eclipse/gemoc/executionframework/engine/ui/launcher/AbstractSequentialGemocLauncher.java#L226
